export interface Province {
  code: string;
  name: string;
  region: string;
}

export const GEOGRAPHIC_REGIONS = [
  'Marmara',
  'Ege',
  'Akdeniz',
  'İç Anadolu',
  'Karadeniz',
  'Doğu Anadolu',
  'Güneydoğu Anadolu',
] as const;

export const PROVINCES: Province[] = [
  // Marmara
  { code: 'istanbul', name: 'İstanbul', region: 'Marmara' },
  { code: 'bursa', name: 'Bursa', region: 'Marmara' },
  { code: 'kocaeli', name: 'Kocaeli', region: 'Marmara' },
  { code: 'sakarya', name: 'Sakarya', region: 'Marmara' },
  { code: 'tekirdag', name: 'Tekirdağ', region: 'Marmara' },
  { code: 'balikesir', name: 'Balıkesir', region: 'Marmara' },
  { code: 'canakkale', name: 'Çanakkale', region: 'Marmara' },
  { code: 'edirne', name: 'Edirne', region: 'Marmara' },
  { code: 'kirklareli', name: 'Kırklareli', region: 'Marmara' },
  { code: 'bilecik', name: 'Bilecik', region: 'Marmara' },
  { code: 'yalova', name: 'Yalova', region: 'Marmara' },
  // Ege
  { code: 'izmir', name: 'İzmir', region: 'Ege' },
  { code: 'manisa', name: 'Manisa', region: 'Ege' },
  { code: 'aydin', name: 'Aydın', region: 'Ege' },
  { code: 'denizli', name: 'Denizli', region: 'Ege' },
  { code: 'mugla', name: 'Muğla', region: 'Ege' },
  { code: 'usak', name: 'Uşak', region: 'Ege' },
  { code: 'kutahya', name: 'Kütahya', region: 'Ege' },
  { code: 'afyonkarahisar', name: 'Afyonkarahisar', region: 'Ege' },
  // Akdeniz
  { code: 'antalya', name: 'Antalya', region: 'Akdeniz' },
  { code: 'adana', name: 'Adana', region: 'Akdeniz' },
  { code: 'mersin', name: 'Mersin', region: 'Akdeniz' },
  { code: 'hatay', name: 'Hatay', region: 'Akdeniz' },
  { code: 'kahramanmaras', name: 'Kahramanmaraş', region: 'Akdeniz' },
  { code: 'osmaniye', name: 'Osmaniye', region: 'Akdeniz' },
  { code: 'isparta', name: 'Isparta', region: 'Akdeniz' },
  { code: 'burdur', name: 'Burdur', region: 'Akdeniz' },
  // İç Anadolu
  { code: 'ankara', name: 'Ankara', region: 'İç Anadolu' },
  { code: 'konya', name: 'Konya', region: 'İç Anadolu' },
  { code: 'kayseri', name: 'Kayseri', region: 'İç Anadolu' },
  { code: 'eskisehir', name: 'Eskişehir', region: 'İç Anadolu' },
  { code: 'sivas', name: 'Sivas', region: 'İç Anadolu' },
  { code: 'aksaray', name: 'Aksaray', region: 'İç Anadolu' },
  { code: 'nevsehir', name: 'Nevşehir', region: 'İç Anadolu' },
  { code: 'nigde', name: 'Niğde', region: 'İç Anadolu' },
  { code: 'yozgat', name: 'Yozgat', region: 'İç Anadolu' },
  { code: 'kirikkale', name: 'Kırıkkale', region: 'İç Anadolu' },
  { code: 'kirsehir', name: 'Kırşehir', region: 'İç Anadolu' },
  { code: 'cankiri', name: 'Çankırı', region: 'İç Anadolu' },
  { code: 'karaman', name: 'Karaman', region: 'İç Anadolu' },
  // Karadeniz
  { code: 'samsun', name: 'Samsun', region: 'Karadeniz' },
  { code: 'trabzon', name: 'Trabzon', region: 'Karadeniz' },
  { code: 'zonguldak', name: 'Zonguldak', region: 'Karadeniz' },
  { code: 'ordu', name: 'Ordu', region: 'Karadeniz' },
  { code: 'giresun', name: 'Giresun', region: 'Karadeniz' },
  { code: 'sinop', name: 'Sinop', region: 'Karadeniz' },
  { code: 'kastamonu', name: 'Kastamonu', region: 'Karadeniz' },
  { code: 'bartin', name: 'Bartın', region: 'Karadeniz' },
  { code: 'bolu', name: 'Bolu', region: 'Karadeniz' },
  { code: 'duzce', name: 'Düzce', region: 'Karadeniz' },
  { code: 'karabuk', name: 'Karabük', region: 'Karadeniz' },
  { code: 'amasya', name: 'Amasya', region: 'Karadeniz' },
  { code: 'tokat', name: 'Tokat', region: 'Karadeniz' },
  { code: 'corum', name: 'Çorum', region: 'Karadeniz' },
  { code: 'rize', name: 'Rize', region: 'Karadeniz' },
  { code: 'artvin', name: 'Artvin', region: 'Karadeniz' },
  { code: 'gumushane', name: 'Gümüşhane', region: 'Karadeniz' },
  // Doğu Anadolu
  { code: 'erzurum', name: 'Erzurum', region: 'Doğu Anadolu' },
  { code: 'malatya', name: 'Malatya', region: 'Doğu Anadolu' },
  { code: 'van', name: 'Van', region: 'Doğu Anadolu' },
  { code: 'elazig', name: 'Elazığ', region: 'Doğu Anadolu' },
  { code: 'erzincan', name: 'Erzincan', region: 'Doğu Anadolu' },
  { code: 'agri', name: 'Ağrı', region: 'Doğu Anadolu' },
  { code: 'kars', name: 'Kars', region: 'Doğu Anadolu' },
  { code: 'igdir', name: 'Iğdır', region: 'Doğu Anadolu' },
  { code: 'ardahan', name: 'Ardahan', region: 'Doğu Anadolu' },
  { code: 'tunceli', name: 'Tunceli', region: 'Doğu Anadolu' },
  { code: 'bingol', name: 'Bingöl', region: 'Doğu Anadolu' },
  { code: 'bitlis', name: 'Bitlis', region: 'Doğu Anadolu' },
  { code: 'mus', name: 'Muş', region: 'Doğu Anadolu' },
  { code: 'hakkari', name: 'Hakkari', region: 'Doğu Anadolu' },
  // Güneydoğu Anadolu
  { code: 'gaziantep', name: 'Gaziantep', region: 'Güneydoğu Anadolu' },
  { code: 'diyarbakir', name: 'Diyarbakır', region: 'Güneydoğu Anadolu' },
  { code: 'sanliurfa', name: 'Şanlıurfa', region: 'Güneydoğu Anadolu' },
  { code: 'mardin', name: 'Mardin', region: 'Güneydoğu Anadolu' },
  { code: 'batman', name: 'Batman', region: 'Güneydoğu Anadolu' },
  { code: 'sirnak', name: 'Şırnak', region: 'Güneydoğu Anadolu' },
  { code: 'siirt', name: 'Siirt', region: 'Güneydoğu Anadolu' },
  { code: 'adiyaman', name: 'Adıyaman', region: 'Güneydoğu Anadolu' },
  { code: 'kilis', name: 'Kilis', region: 'Güneydoğu Anadolu' },
];
